In [1]:
# Import Dependencies
import pandas as pd
import csv
import os
from splinter import Browser
from bs4 import BeautifulSoup
from webdriver_manager.chrome import ChromeDriverManager

In [2]:
executable_path = {'executable_path': ChromeDriverManager().install()}
browser = Browser('chrome', **executable_path, headless=False)

====== WebDriver manager ======
Current google-chrome version is 100.0.4896
Get LATEST chromedriver version for 100.0.4896 google-chrome
Trying to download new driver from https://chromedriver.storage.googleapis.com/100.0.4896.60/chromedriver_win32.zip
Driver has been saved in cache [C:\Users\14043\.wdm\drivers\chromedriver\win32\100.0.4896.60]

In [3]:
url = 'https://en.wikipedia.org/wiki/List_of_national_parks_of_the_United_States'
browser.visit(url)

In [32]:
tables = pd.read_html(url)
tables

[                                          0
 0  Map all coordinates using: OpenStreetMap
 1              Download coordinates as: KML,
                     Name  Image  \
 0                 Acadia    NaN
 1         American Samoa    NaN
 2                 Arches    NaN
 3               Badlands    NaN
 4               Big Bend    NaN
 ..                   ...    ...
 58             Wind Cave    NaN
 59  Wrangell–St. Elias *    NaN
 60           Yellowstone    NaN
 61            Yosemite *    NaN
 62                  Zion    NaN

                                              Location  \
 0   Maine.mw-parser-output .geo-default,.mw-parser...
 1   American Samoa14°15′S 170°41′W﻿ / ﻿14.25°S 170...
 2           Utah38°41′N 109°34′W﻿ / ﻿38.68°N 109.57°W
 3   South Dakota43°45′N 102°30′W﻿ / ﻿43.75°N 102.50°W
 4          Texas29°15′N 103°15′W﻿ / ﻿29.25°N 103.25°W
 ..                                                ...
 58  South Dakota43°34′N 103°29′W﻿ / ﻿43.57°N 103.48°W
 59        Alaska61°00′N 142°00′W﻿ / ﻿61.00°N 142.00°W
 60  Wyoming, Montana, Idaho44°36′N 110°30′W﻿ / ﻿44...
 61    California37°50′N 119°30′W﻿ / ﻿37.83°N 119.50°W
 62          Utah37°18′N 113°03′W﻿ / ﻿37.30°N 113.05°W

    Date established as park[7][12]                    Area (2021)[13]  \
 0                February 26, 1919        49,071.40 acres (198.6 km2)
 1                 October 31, 1988          8,256.67 acres (33.4 km2)
 2                November 12, 1971        76,678.98 acres (310.3 km2)
 3                November 10, 1978       242,755.94 acres (982.4 km2)
 4                    June 12, 1944     801,163.21 acres (3,242.2 km2)
 ..                             ...                                ...
 58                 January 9, 1903        33,970.84 acres (137.5 km2)
 59                December 2, 1980  8,323,146.48 acres (33,682.6 km2)
 60                   March 1, 1872   2,219,790.71 acres (8,983.2 km2)
 61                 October 1, 1890     761,747.50 acres (3,082.7 km2)
 62               November 19, 1919       147,242.66 acres (595.9 km2)

     Recreation visitors (2021)[11]  \
 0                          4069098
 1                             8495
 2                          1806865
 3                          1224226
 4                           581220
 ..                             ...
 58                          709001
 59                           50189
 60                         4860242
 61                         3287595
 62                         5039835

                                           Description
 0   Covering most of Mount Desert Island and other...
 1   The southernmost national park is on three Sam...
 2   This site features more than 2,000 natural san...
 3   The Badlands are a collection of buttes, pinna...
 4   Named for the prominent bend in the Rio Grande...
 ..                                                ...
 58  Wind Cave is distinctive for its calcite fin f...
 59  The largest national park in the system protec...
 60  Situated on the Yellowstone Caldera, the park ...
 61  Yosemite features sheer granite cliffs, except...
 62  Located at the junction of the Colorado Platea...

 [63 rows x 7 columns],
                   State  Total parks Exclusive parks Shared parks
 0            California            9               8            1
 1                Alaska            8               8            —
 2                  Utah            5               5            —
 3              Colorado            4               4            —
 4               Arizona            3               3            —
 5               Florida            3               3            —
 6            Washington            3               3            —
 7                Hawaii            2               2            —
 8            New Mexico            2               2            —
 9          South Dakota            2               2            —
 10                Texas            2               2            —
 11              Montana            2               1            1
 12               Nevada            2               1            1
 13              Wyoming            2               1            1
 14       American Samoa            1               1            —
 15             Arkansas            1               1            —
 16              Indiana            1               1            —
 17             Kentucky            1               1            —
 18                Maine            1               1            —
 19             Michigan            1               1            —
 20            Minnesota            1               1            —
 21             Missouri            1               1            —
 22         North Dakota            1               1            —
 23                 Ohio            1               1            —
 24               Oregon            1               1            —
 25       South Carolina            1               1            —
 26  U.S. Virgin Islands            1               1            —
 27             Virginia            1               1            —
 28        West Virginia            1               1            —
 29                Idaho            1               —            1
 30       North Carolina            1               —            1
 31            Tennessee            1               —            1,
     0                                                  1
 0 NaN  Wikivoyage has a travel guide for United State...,
     0                                                  1
 0 NaN  Wikimedia Commons has media related to Nationa...,
   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vteNational parks of the United States  \
 0  Acadia American Samoa Arches Badlands Big Bend...
 1  List of national parks of the United States (b...

   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vteNational parks of the United States.1  \
 0  Acadia American Samoa Arches Badlands Big Bend...
 1  List of national parks of the United States (b...

   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vteNational parks of the United States.2
 0                                                NaN
 1  List of national parks of the United States (b...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ,
      vteFederal protected areas in the United States  \
 0  Conservation Areas Estuarine Research Reserves...

    vteFederal protected areas in the United States.1
 0  Conservation Areas Estuarine Research Reserves...  ]

In [5]:
type (tables)

list

In [33]:
df = tables[1]
df.head()

,Name,Image,Location,Date established as park[7][12],Area (2021)[13],Recreation visitors (2021)[11],Description
0,Acadia,NaN,"Maine.mw-parser-output .geo-default,.mw-parser...","February 26, 1919","49,071.40 acres (198.6 km2)",4069098,Covering most of Mount Desert Island and other...
1,American Samoa,NaN,American Samoa14°15′S 170°41′W﻿ / ﻿14.25°S 170...,"October 31, 1988","8,256.67 acres (33.4 km2)",8495,The southernmost national park is on three Sam...
2,Arches,NaN,Utah38°41′N 109°34′W﻿ / ﻿38.68°N 109.57°W,"November 12, 1971","76,678.98 acres (310.3 km2)",1806865,"This site features more than 2,000 natural san..."
3,Badlands,NaN,South Dakota43°45′N 102°30′W﻿ / ﻿43.75°N 102.50°W,"November 10, 1978","242,755.94 acres (982.4 km2)",1224226,"The Badlands are a collection of buttes, pinna..."
4,Big Bend,NaN,Texas29°15′N 103°15′W﻿ / ﻿29.25°N 103.25°W,"June 12, 1944","801,163.21 acres (3,242.2 km2)",581220,Named for the prominent bend in the Rio Grande...

In [34]:
to_drop = ['Recreation visitors (2021)[11]', 'Area (2021)[13]', 'Description', 'Image']
df.drop(to_drop, inplace=True, axis=1)
df.head()

,Name,Location,Date established as park[7][12]
0,Acadia,"Maine.mw-parser-output .geo-default,.mw-parser...","February 26, 1919"
1,American Samoa,American Samoa14°15′S 170°41′W﻿ / ﻿14.25°S 170...,"October 31, 1988"
2,Arches,Utah38°41′N 109°34′W﻿ / ﻿38.68°N 109.57°W,"November 12, 1971"
3,Badlands,South Dakota43°45′N 102°30′W﻿ / ﻿43.75°N 102.50°W,"November 10, 1978"
4,Big Bend,Texas29°15′N 103°15′W﻿ / ﻿29.25°N 103.25°W,"June 12, 1944"

In [37]:
new = df["Location"].str.split("/", n = 2, expand = True)
  
df["Coordinates"]= new[1]
  
df.head()

,Name,Location,Date established as park[7][12],Initial Coordinates,Coordinates
0,Acadia,"Maine.mw-parser-output .geo-default,.mw-parser...","February 26, 1919","Maine.mw-parser-output .geo-default,.mw-parser...",﻿44.35°N 68.21°W
1,American Samoa,American Samoa14°15′S 170°41′W﻿ / ﻿14.25°S 170...,"October 31, 1988",American Samoa14°15′S 170°41′W﻿,﻿14.25°S 170.68°W
2,Arches,Utah38°41′N 109°34′W﻿ / ﻿38.68°N 109.57°W,"November 12, 1971",Utah38°41′N 109°34′W﻿,﻿38.68°N 109.57°W
3,Badlands,South Dakota43°45′N 102°30′W﻿ / ﻿43.75°N 102.50°W,"November 10, 1978",South Dakota43°45′N 102°30′W﻿,﻿43.75°N 102.50°W
4,Big Bend,Texas29°15′N 103°15′W﻿ / ﻿29.25°N 103.25°W,"June 12, 1944",Texas29°15′N 103°15′W﻿,﻿29.25°N 103.25°W

In [38]:
to_drop = ['Location', 'Initial Coordinates']
df.drop(to_drop, inplace=True, axis=1)
df.head()

             Name Date established as park[7][12]         Coordinates
0          Acadia               February 26, 1919    ﻿44.35°N 68.21°W
1  American Samoa                October 31, 1988   ﻿14.25°S 170.68°W
2          Arches               November 12, 1971   ﻿38.68°N 109.57°W
3        Badlands               November 10, 1978   ﻿43.75°N 102.50°W
4        Big Bend                   June 12, 1944   ﻿29.25°N 103.25°W

In [42]:
df.to_csv ("nationalParksInitial.csv", index = False, header=True)